#include "EEPROM.h"

#define EEPROM_SIZE 128

#define E_ADDR_MOTOR1_ENABLED 0
#define E_ADDR_MOTOR2_ENABLED 1
#define E_ADDR_SERVO1_ENABLED 2
#define E_ADDR_SERVO2_ENABLED 3
#define E_ADDR_MOTOR1_MAX 4
#define E_ADDR_MOTOR2_MAX 5
#define E_ADDR_SERVO1_LEFT 6
#define E_ADDR_SERVO1_RIGHT 7
#define E_ADDR_SERVO2_LEFT 8
#define E_ADDR_SERVO2_RIGHT 9
#define E_ADDR_PERIPHERIALS 10
#define E_ADDR_SPEED 11
#define E_ADDR_HANDLING 12
#define E_ADDR_CLIMB 13
#define E_ADDR_OFFROAD 14
#define E_ADDR_BATTERY 15
#define E_ADDR_IMAGE 20
#define E_ADDR_NAME 40
#define E_ADDR_WIFI_SSID 64
#define E_ADDR_WIFI_PASSWORD 88
#define E_ADDR_WIFI_SERVER 110
